import { IRoomItem } from 'src/app/interfaces/room-item';

export const RoomBuiltExample: IRoomItem[] = [
    {
        id: 1,
        type: 6,
        status: 0,
        content: '1',
        locked: false,
        parent: '.wrapper',
        bgColor: 0,
        contentColor: 0,
        position: { x: -1, y: -1 },
        selected: false,
    },
    {
        id: 2,
        type: 6,
        status: 0,
        content: '2',
        locked: false,
        parent: '.wrapper',
        bgColor: 0,
        contentColor: 0,
        position: { x: 52, y: -1 },
        selected: false
    },
    {
        id: 3,
        type: 6,
        status: 0,
        content: '3',
        locked: false,
        parent: '.wrapper',
        bgColor: 0,
        contentColor: 0,
        position: { x: 106, y: -1 },
        selected: false
    },
    {
        id: 4,
        type: 6,
        status: 0,
        content: '4',
        locked: false,
        parent: '.wrapper',
        bgColor: 0,
        contentColor: 0,
        position: { x: 160, y: -1 },
        selected: false
    },
    {
        id: 5,
        type: 6,
        status: 0,
        content: '5',
        locked: false,
        parent: '.wrapper',
        bgColor: 0,
        contentColor: 0,
        position: { x: 215, y: -1 },
        selected: false
    },
    {
        id: 6,
        type: 6,
        status: 0,
        content: '6',
        locked: false,
        parent: '.wrapper',
        bgColor: 0,
        contentColor: 0,
        position: { x: 392, y: 0 },
        selected: false
    },
    {
        id: 7,
        type: 5,
        status: 0,
        content: '7',
        locked: false,
        parent: '.wrapper',
        bgColor: 0,
        contentColor: 0,
        position: { x: -1, y: 12 },
        selected: false
    },
    {
        id: 8,
        type: 5,
        status: 0,
        content: '8',
        locked: false,
        parent: '.wrapper',
        bgColor: 0,
        contentColor: 0,
        position: { x: -1, y: 64 },
        selected: false
    },
    {
        id: 9,
        type: 5,
        status: 0,
        content: '9',
        locked: false,
        parent: '.wrapper',
        bgColor: 0,
        contentColor: 0,
        position: { x: -1, y: 386 },
        selected: false
    },
    {
        id: 10,
        type: 5,
        status: 0,
        content: '10',
        locked: false,
        parent: '.wrapper',
        bgColor: 0,
        contentColor: 0,
        position: { x: -1, y: 119 },
        selected: false
    },
    {
        id: 11,
        type: 5,
        status: 0,
        content: '11',
        locked: false,
        parent: '.wrapper',
        bgColor: 0,
        contentColor: 0,
        position: { x: -1, y: 174 },
        selected: false
    },
    {
        id: 12,
        type: 5,
        status: 0,
        content: '12',
        locked: false,
        parent: '.wrapper',
        bgColor: 0,
        contentColor: 0,
        position: { x: -1, y: 227 },
        selected: false
    },
    {
        id: 13,
        type: 5,
        status: 0,
        content: '13',
        locked: false,
        parent: '.wrapper',
        bgColor: 0,
        contentColor: 0,
        position: { x: -1, y: 279 },
        selected: false
    },
    {
        id: 14,
        type: 5,
        status: 0,
        content: '14',
        locked: false,
        parent: '.wrapper',
        bgColor: 0,
        contentColor: 0,
        position: { x: -1, y: 333 },
        selected: false
    },
    {
        id: 15,
        type: 6,
        status: 0,
        content: '15',
        locked: false,
        parent: '.wrapper',
        bgColor: 0,
        contentColor: 0,
        position: { x: 11, y: 427.25 },
        selected: false
    },
    {
        id: 16,
        type: 6,
        status: 0,
        content: '16',
        locked: false,
        parent: '.wrapper',
        bgColor: 0,
        contentColor: 0,
        position: { x: 64, y: 427.25 },
        selected: false
    },
    {
        id: 17,
        type: 6,
        status: 0,
        content: '17',
        locked: false,
        parent: '.wrapper',
        bgColor: 0,
        contentColor: 0,
        position: { x: 118, y: 427.5 },
        selected: false
    },
    {
        id: 18,
        type: 6,
        status: 0,
        content: '18',
        locked: false,
        parent: '.wrapper',
        bgColor: 0,
        contentColor: 0,
        position: { x: 171, y: 427.5 },
        selected: false
    },
    {
        id: 19,
        type: 6,
        status: 0,
        content: '19',
        locked: false,
        parent: '.wrapper',
        bgColor: 0,
        contentColor: 0,
        position: { x: 224, y: 427.25 },
        selected: false
    },
    {
        id: 20,
        type: 6,
        status: 0,
        content: '20',
        locked: false,
        parent: '.wrapper',
        bgColor: 0,
        contentColor: 0,
        position: { x: 278, y: 427.25 },
        selected: false
    },
    {
        id: 21,
        type: 6,
        status: 0,
        content: '21',
        locked: false,
        parent: '.wrapper',
        bgColor: 0,
        contentColor: 0,
        position: { x: 332, y: 426.75 },
        selected: false
    },
    {
        id: 22,
        type: 6,
        status: 0,
        content: '22',
        locked: false,
        parent: '.wrapper',
        bgColor: 0,
        contentColor: 0,
        position: { x: 385, y: 427.5 },
        selected: false
    },
    {
        id: 23,
        type: 6,
        status: 0,
        content: '23',
        locked: false,
        parent: '.wrapper',
        bgColor: 0,
        contentColor: 0,
        position: { x: 439, y: 427.25 },
        selected: false
    },
    {
        id: 24,
        type: 6,
        status: 0,
        content: '24',
        locked: false,
        parent: '.wrapper',
        bgColor: 0,
        contentColor: 0,
        position: { x: 493, y: 427.5 },
        selected: false
    },
    {
        id: 25,
        type: 6,
        status: 0,
        content: '25',
        locked: false,
        parent: '.wrapper',
        bgColor: 0,
        contentColor: 0,
        position: { x: 545, y: 427.25 },
        selected: false
    },
    {
        id: 26,
        type: 6,
        status: 0,
        content: '26',
        locked: false,
        parent: '.wrapper',
        bgColor: 0,
        contentColor: 0,
        position: { x: 753.1999931335449, y: 427.5 },
        selected: false
    },
    {
        id: 27,
        type: 6,
        status: 0,
        content: '27',
        locked: false,
        parent: '.wrapper',
        bgColor: 0,
        contentColor: 0,
        position: { x: 703, y: 427.25 },
        selected: false
    },
    {
        id: 28,
        type: 6,
        status: 0,
        content: '28',
        locked: false,
        parent: '.wrapper',
        bgColor: 0,
        contentColor: 0,
        position: { x: 650, y: 427.5 },
        selected: false
    },
    {
        id: 29,
        type: 6,
        status: 0,
        content: '29',
        locked: false,
        parent: '.wrapper',
        bgColor: 0,
        contentColor: 0,
        position: { x: 597, y: 426.75 },
        selected: false
    },
    {
        id: 30,
        type: 6,
        status: 0,
        content: '30',
        locked: false,
        parent: '.wrapper',
        bgColor: 0,
        contentColor: 0,
        position: { x: 768.2000007629395, y: 427.25 },
        selected: false
    },
    {
        id: 31,
        type: 5,
        status: 0,
        content: '31',
        locked: false,
        parent: '.wrapper',
        bgColor: 0,
        contentColor: 0,
        position: { x: 809.5999240875244, y: 374 },
        selected: false
    },
    {
        id: 32,
        type: 5,
        status: 0,
        content: '32',
        locked: false,
        parent: '.wrapper',
        bgColor: 0,
        contentColor: 0,
        position: { x: 809.5999240875244, y: 322 },
        selected: false
    },
    {
        id: 33,
        type: 5,
        status: 0,
        content: '33',
        locked: false,
        parent: '.wrapper',
        bgColor: 0,
        contentColor: 0,
        position: { x: 809.5999546051025, y: 268 },
        selected: false
    },
    {
        id: 34,
        type: 5,
        status: 0,
        content: '34',
        locked: false,
        parent: '.wrapper',
        bgColor: 0,
        contentColor: 0,
        position: { x: 809.5999240875244, y: 213 },
        selected: false
    },
    {
        id: 35,
        type: 5,
        status: 0,
        content: '35',
        locked: false,
        parent: '.wrapper',
        bgColor: 0,
        contentColor: 0,
        position: { x: 809.5999546051025, y: 165 },
        selected: false
    },
    {
        id: 36,
        type: 5,
        status: 0,
        content: '36',
        locked: false,
        parent: '.wrapper',
        bgColor: 0,
        contentColor: 0,
        position: { x: 808.8999166488647, y: 110 },
        selected: false
    },
    {
        id: 38,
        type: 6,
        status: 0,
        content: '38',
        locked: false,
        parent: '.wrapper',
        bgColor: 0,
        contentColor: 0,
        position: { x: 768.1999998092651, y: -1 },
        selected: false
    },
    {
        id: 39,
        type: 6,
        status: 0,
        content: '39',
        locked: false,
        parent: '.wrapper',
        bgColor: 0,
        contentColor: 0,
        position: { x: 716, y: -1 },
        selected: false
    },
    {
        id: 40,
        type: 6,
        status: 0,
        content: '40',
        locked: false,
        parent: '.wrapper',
        bgColor: 0,
        contentColor: 0,
        position: { x: 663, y: -1 },
        selected: false
    },
    {
        id: 41,
        type: 6,
        status: 0,
        content: '41',
        locked: false,
        parent: '.wrapper',
        bgColor: 0,
        contentColor: 0,
        position: { x: 609, y: -1 },
        selected: false
    },
    {
        id: 42,
        type: 6,
        status: 0,
        content: '42',
        locked: false,
        parent: '.wrapper',
        bgColor: 0,
        contentColor: 0,
        position: { x: 556, y: -1 },
        selected: false
    },
    {
        id: 43,
        type: 6,
        status: 0,
        content: '43',
        locked: false,
        parent: '.wrapper',
        bgColor: 0,
        contentColor: 0,
        position: { x: 502, y: -1 },
        selected: false
    },
    {
        id: 44,
        type: 6,
        status: 0,
        content: '44',
        locked: false,
        parent: '.wrapper',
        bgColor: 0,
        contentColor: 0,
        position: { x: 447, y: -1 },
        selected: false
    },
    {
        id: 45,
        type: 5,
        status: 0,
        content: '45',
        locked: false,
        parent: '.wrapper',
        bgColor: 0,
        contentColor: 0,
        position: { x: 257, y: 12 },
        selected: false
    },
    {
        id: 46,
        type: 5,
        status: 0,
        content: '46',
        locked: false,
        parent: '.wrapper',
        bgColor: 0,
        contentColor: 0,
        position: { x: 257, y: 66 },
        selected: false
    },
    {
        id: 48,
        type: 5,
        status: 0,
        content: '48',
        locked: false,
        parent: '.wrapper',
        bgColor: 0,
        contentColor: 0,
        position: { x: 244, y: 12 },
        selected: false
    },
    {
        id: 49,
        type: 5,
        status: 0,
        content: '49',
        locked: false,
        parent: '.wrapper',
        bgColor: 0,
        contentColor: 0,
        position: { x: 244, y: 65 },
        selected: false
    },
    {
        id: 51,
        type: 1,
        status: 0,
        content: '31',
        locked: false,
        parent: '.wrapper',
        bgColor: 0,
        contentColor: 0,
        position: { x: 34, y: 16 },
        selected: false
    },
    {
        id: 52,
        type: 0,
        status: 0,
        content: '30',
        locked: false,
        parent: '.wrapper',
        bgColor: 0,
        contentColor: 0,
        position: { x: 112, y: 17 },
        selected: false
    },
    {
        id: 53,
        type: 2,
        status: 0,
        content: '33',
        locked: false,
        parent: '.wrapper',
        bgColor: 0,
        contentColor: 0,
        position: { x: 136, y: 73 },
        selected: false
    },
    {
        id: 54,
        type: 1,
        status: 0,
        content: '32',
        locked: false,
        parent: '.wrapper',
        bgColor: 0,
        contentColor: 0,
        position: { x: 34, y: 144 },
        selected: false
    },
    {
        id: 55,
        type: 3,
        status: 0,
        content: '20',
        locked: false,
        parent: '.wrapper',
        bgColor: 0,
        contentColor: 0,
        position: { x: 33, y: 271 },
        selected: false
    },
    {
        id: 56,
        type: 3,
        status: 0,
        content: '22',
        locked: false,
        parent: '.wrapper',
        bgColor: 0,
        contentColor: 0,
        position: { x: 33, y: 356 },
        selected: false
    },
    {
        id: 57,
        type: 3,
        status: 0,
        content: '21',
        locked: false,
        parent: '.wrapper',
        bgColor: 0,
        contentColor: 0,
        position: { x: 120, y: 272 },
        selected: false
    },
    {
        id: 58,
        type: 3,
        status: 0,
        content: '23',
        locked: false,
        parent: '.wrapper',
        bgColor: 0,
        contentColor: 0,
        position: { x: 121, y: 356 },
        selected: false
    },
    {
        id: 59,
        type: 5,
        status: 0,
        content: '59',
        locked: false,
        parent: '.wrapper',
        bgColor: 0,
        contentColor: 0,
        position: { x: 197, y: 373 },
        selected: false
    },
    {
        id: 60,
        type: 5,
        status: 0,
        content: '60',
        locked: false,
        parent: '.wrapper',
        bgColor: 0,
        contentColor: 0,
        position: { x: 197, y: 318 },
        selected: false
    },
    {
        id: 61,
        type: 5,
        status: 0,
        content: '61',
        locked: false,
        parent: '.wrapper',
        bgColor: 0,
        contentColor: 0,
        position: { x: 197, y: 263 },
        selected: false
    },
    {
        id: 63,
        type: 6,
        status: 0,
        content: '63',
        locked: false,
        parent: '.wrapper',
        bgColor: 0,
        contentColor: 0,
        position: { x: 179, y: 249 },
        selected: false
    },
    {
        id: 64,
        type: 6,
        status: 0,
        content: '64',
        locked: false,
        parent: '.wrapper',
        bgColor: 0,
        contentColor: 0,
        position: { x: 234, y: 249 },
        selected: false
    },
    {
        id: 65,
        type: 3,
        status: 0,
        content: '10',
        locked: false,
        parent: '.wrapper',
        bgColor: 0,
        contentColor: 0,
        position: { x: 405, y: 32 },
        selected: false
    },
    {
        id: 66,
        type: 3,
        status: 0,
        content: '11',
        locked: false,
        parent: '.wrapper',
        bgColor: 0,
        contentColor: 0,
        position: { x: 405, y: 120 },
        selected: false
    },
    {
        id: 67,
        type: 3,
        status: 0,
        content: '12',
        locked: false,
        parent: '.wrapper',
        bgColor: 0,
        contentColor: 0,
        position: { x: 503, y: 32 },
        selected: false
    },
    {
        id: 68,
        type: 3,
        status: 0,
        content: '13',
        locked: false,
        parent: '.wrapper',
        bgColor: 0,
        contentColor: 0,
        position: { x: 504, y: 120 },
        selected: false
    },
    {
        id: 69,
        type: 3,
        status: 0,
        content: '14',
        locked: false,
        parent: '.wrapper',
        bgColor: 0,
        contentColor: 0,
        position: { x: 599, y: 32 },
        selected: false
    },
    {
        id: 70,
        type: 3,
        status: 0,
        content: '15',
        locked: false,
        parent: '.wrapper',
        bgColor: 0,
        contentColor: 0,
        position: { x: 599, y: 121 },
        selected: false
    },
    {
        id: 71,
        type: 7,
        status: 0,
        content: 'Entrance',
        locked: false,
        parent: '.wrapper',
        bgColor: 8,
        contentColor: 0,
        position: { x: 744, y: 46 },
        selected: false
    },
    {
        id: 72,
        type: 5,
        status: 0,
        content: '72',
        locked: false,
        parent: '.wrapper',
        bgColor: 0,
        contentColor: 0,
        position: { x: 797, y: 373 },
        selected: false
    },
    {
        id: 73,
        type: 5,
        status: 0,
        content: '73',
        locked: false,
        parent: '.wrapper',
        bgColor: 0,
        contentColor: 0,
        position: { x: 797, y: 318 },
        selected: false
    },
    {
        id: 75,
        type: 4,
        status: 0,
        content: 'B8',
        locked: false,
        parent: '.wrapper',
        bgColor: 0,
        contentColor: 0,
        position: { x: 754, y: 203 },
        selected: false
    },
    {
        id: 76,
        type: 6,
        status: 0,
        content: '76',
        locked: false,
        parent: '.wrapper',
        bgColor: 0,
        contentColor: 0,
        position: { x: 756, y: 259 },
        selected: false
    },
    {
        id: 77,
        type: 5,
        status: 0,
        content: '77',
        locked: false,
        parent: '.wrapper',
        bgColor: 0,
        contentColor: 0,
        position: { x: 784, y: 372 },
        selected: false
    },
    {
        id: 78,
        type: 5,
        status: 0,
        content: '78',
        locked: false,
        parent: '.wrapper',
        bgColor: 0,
        contentColor: 0,
        position: { x: 784, y: 318 },
        selected: false
    },
    {
        id: 79,
        type: 5,
        status: 0,
        content: '79',
        locked: false,
        parent: '.wrapper',
        bgColor: 0,
        contentColor: 0,
        position: { x: 771, y: 372 },
        selected: false
    },
    {
        id: 80,
        type: 5,
        status: 0,
        content: '80',
        locked: false,
        parent: '.wrapper',
        bgColor: 0,
        contentColor: 0,
        position: { x: 771, y: 318 },
        selected: false
    },
    {
        id: 81,
        type: 6,
        status: 0,
        content: '81',
        locked: false,
        parent: '.wrapper',
        bgColor: 0,
        contentColor: 0,
        position: { x: 716, y: 319 },
        selected: false
    },
    {
        id: 82,
        type: 6,
        status: 0,
        content: '82',
        locked: false,
        parent: '.wrapper',
        bgColor: 0,
        contentColor: 0,
        position: { x: 663, y: 319 },
        selected: false
    },
    {
        id: 83,
        type: 6,
        status: 0,
        content: '83',
        locked: false,
        parent: '.wrapper',
        bgColor: 0,
        contentColor: 0,
        position: { x: 608, y: 319 },
        selected: false
    },
    {
        id: 84,
        type: 6,
        status: 0,
        content: '84',
        locked: false,
        parent: '.wrapper',
        bgColor: 0,
        contentColor: 0,
        position: { x: 556, y: 319 },
        selected: false
    },
    {
        id: 85,
        type: 6,
        status: 0,
        content: '85',
        locked: false,
        parent: '.wrapper',
        bgColor: 0,
        contentColor: 0,
        position: { x: 502, y: 319 },
        selected: false
    },
    {
        id: 86,
        type: 6,
        status: 0,
        content: '86',
        locked: false,
        parent: '.wrapper',
        bgColor: 0,
        contentColor: 0,
        position: { x: 448, y: 319 },
        selected: false
    },
    {
        id: 87,
        type: 6,
        status: 0,
        content: '87',
        locked: false,
        parent: '.wrapper',
        bgColor: 0,
        contentColor: 0,
        position: { x: 393, y: 319 },
        selected: false
    },
    {
        id: 88,
        type: 6,
        status: 0,
        content: '88',
        locked: false,
        parent: '.wrapper',
        bgColor: 0,
        contentColor: 0,
        position: { x: 716, y: 333 },
        selected: false
    },
    {
        id: 89,
        type: 6,
        status: 0,
        content: '89',
        locked: false,
        parent: '.wrapper',
        bgColor: 0,
        contentColor: 0,
        position: { x: 662, y: 333 },
        selected: false
    },
    {
        id: 90,
        type: 6,
        status: 0,
        content: '90',
        locked: false,
        parent: '.wrapper',
        bgColor: 0,
        contentColor: 0,
        position: { x: 607, y: 333 },
        selected: false
    },
    {
        id: 91,
        type: 6,
        status: 0,
        content: '91',
        locked: false,
        parent: '.wrapper',
        bgColor: 0,
        contentColor: 0,
        position: { x: 552, y: 333 },
        selected: false
    },
    {
        id: 92,
        type: 6,
        status: 0,
        content: '92',
        locked: false,
        parent: '.wrapper',
        bgColor: 0,
        contentColor: 0,
        position: { x: 498, y: 333 },
        selected: false
    },
    {
        id: 93,
        type: 6,
        status: 0,
        content: '93',
        locked: false,
        parent: '.wrapper',
        bgColor: 0,
        contentColor: 0,
        position: { x: 443, y: 333 },
        selected: false
    },
    {
        id: 94,
        type: 6,
        status: 0,
        content: '94',
        locked: false,
        parent: '.wrapper',
        bgColor: 0,
        contentColor: 0,
        position: { x: 393, y: 332 },
        selected: false
    },
    {
        id: 95,
        type: 7,
        status: 0,
        content: 'Kitchen',
        locked: false,
        parent: '.wrapper',
        bgColor: 0,
        contentColor: 0,
        position: { x: 472, y: 377 },
        selected: false
    },
    {
        id: 96,
        type: 5,
        status: 0,
        content: '96',
        locked: false,
        parent: '.wrapper',
        bgColor: 0,
        contentColor: 0,
        position: { x: 341, y: 268 },
        selected: false
    },
    {
        id: 97,
        type: 6,
        status: 0,
        content: '97',
        locked: false,
        parent: '.wrapper',
        bgColor: 0,
        contentColor: 0,
        position: { x: 701, y: 259 },
        selected: false
    },
    {
        id: 98,
        type: 6,
        status: 0,
        content: '98',
        locked: false,
        parent: '.wrapper',
        bgColor: 0,
        contentColor: 0,
        position: { x: 646, y: 259 },
        selected: false
    },
    {
        id: 99,
        type: 6,
        status: 0,
        content: '99',
        locked: false,
        parent: '.wrapper',
        bgColor: 0,
        contentColor: 0,
        position: { x: 591, y: 259 },
        selected: false
    },
    {
        id: 100,
        type: 6,
        status: 0,
        content: '100',
        locked: false,
        parent: '.wrapper',
        bgColor: 0,
        contentColor: 0,
        position: { x: 537, y: 259 },
        selected: false
    },
    {
        id: 101,
        type: 6,
        status: 0,
        content: '101',
        locked: false,
        parent: '.wrapper',
        bgColor: 0,
        contentColor: 0,
        position: { x: 483, y: 259 },
        selected: false
    },
    {
        id: 102,
        type: 6,
        status: 0,
        content: '102',
        locked: false,
        parent: '.wrapper',
        bgColor: 0,
        contentColor: 0,
        position: { x: 440, y: 260 },
        selected: false
    },
    {
        id: 103,
        type: 6,
        status: 0,
        content: '103',
        locked: false,
        parent: '.wrapper',
        bgColor: 0,
        contentColor: 0,
        position: { x: 393, y: 261 },
        selected: false
    },
    {
        id: 104,
        type: 7,
        status: 0,
        content: 'Bar',
        locked: false,
        parent: '.wrapper',
        bgColor: 0,
        contentColor: 0,
        position: { x: 577, y: 285 },
        selected: false
    },
    {
        id: 105,
        type: 4,
        status: 0,
        content: 'B7',
        locked: false,
        parent: '.wrapper',
        bgColor: 0,
        contentColor: 0,
        position: { x: 698, y: 204 },
        selected: false
    },
    {
        id: 106,
        type: 4,
        status: 0,
        content: 'B6',
        locked: false,
        parent: '.wrapper',
        bgColor: 0,
        contentColor: 0,
        position: { x: 642, y: 204 },
        selected: false
    },
    {
        id: 107,
        type: 4,
        status: 0,
        content: 'B5',
        locked: false,
        parent: '.wrapper',
        bgColor: 0,
        contentColor: 0,
        position: { x: 585, y: 204 },
        selected: false
    },
    {
        id: 108,
        type: 4,
        status: 0,
        content: 'B4',
        locked: false,
        parent: '.wrapper',
        bgColor: 0,
        contentColor: 0,
        position: { x: 529, y: 204 },
        selected: false
    },
    {
        id: 109,
        type: 4,
        status: 0,
        content: 'B3',
        locked: false,
        parent: '.wrapper',
        bgColor: 0,
        contentColor: 0,
        position: { x: 472, y: 204 },
        selected: false
    },
    {
        id: 110,
        type: 4,
        status: 0,
        content: 'B2',
        locked: false,
        parent: '.wrapper',
        bgColor: 0,
        contentColor: 0,
        position: { x: 416, y: 203 },
        selected: false
    },
    {
        id: 111,
        type: 4,
        status: 0,
        content: 'B1',
        locked: false,
        parent: '.wrapper',
        bgColor: 0,
        contentColor: 0,
        position: { x: 358, y: 203 },
        selected: false
    },
    {
        id: 112,
        type: 6,
        status: 0,
        content: '112',
        locked: false,
        parent: '.wrapper',
        bgColor: 0,
        contentColor: 0,
        position: { x: 341, y: 260 },
        selected: false
    },
    {
        id: 113,
        type: 6,
        status: 0,
        content: '113',
        locked: false,
        parent: '.wrapper',
        bgColor: 0,
        contentColor: 0,
        position: { x: 341, y: 319 },
        selected: false
    },
    {
        id: 114,
        type: 6,
        status: 0,
        content: '114',
        locked: false,
        parent: '.wrapper',
        bgColor: 0,
        contentColor: 0,
        position: { x: 341, y: 332 },
        selected: false
    },
];
